name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'posts/*.md'              # Ignore direct markdown changes
      - 'docs/**'                 # Ignore documentation
      - '*.md'                    # Ignore any other markdown files
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setting Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Building... 🔨
        run: |
          ./gradlew wasmJsBrowserDistribution
          cp app/src/wasmJsMain/resources/styles.css app/build/dist/wasmJs/productionExecutable/styles.css
          touch app/build/dist/wasmJs/productionExecutable/.nojekyll

      - name: Configuring Github Pages
        uses: actions/configure-pages@v4

      - name: Uploading artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'app/build/dist/wasmJs/productionExecutable'
          
      - name: Deploying 🚀
        id: deployment
        uses: actions/deploy-pages@v4
